name: Doxygen generation

on: [push]

jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v2
        
    - name: Doxygen generation
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:

        doxyfile-path: "./doc/Doxyfile"
        working-directory: "./doc/"
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html    
